# Generated by Django 5.0.6 on 2024-05-18 09:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_player_buzzered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='buzzered',
        ),
        migrations.AddField(
            model_name='lobby',
            name='buzzered_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.player'),
        ),
        migrations.AddField(
            model_name='lobby',
            name='buzzered_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
