# Generated by Django 5.0.6 on 2024-05-18 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_lobby_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobby',
            name='board',
            field=models.JSONField(blank=True, default='{"Categories": [{"name": "Gaming", "questions": [["Welches Unternehmen hat die PlayStation entwickelt?", "Sony", 100, false], ["In welchem Jahr wurde das erste \'Grand Theft Auto\'-Spiel ver\\u00f6ffentlicht?", 1997, 200, false], ["Wie hei\\u00dft das Rollenspiel, das von Bethesda Game Studios entwickelt wurde und in der postapokalyptischen Zukunft spielt?", "Fallout", 300, false], ["In welchem Spiel ist die \'Pip-Boy\' ein wesentliches Ausr\\u00fcstungsst\\u00fcck?", "Fallout", 400, false], ["Wie viele Sterne kann man in \'Super Mario 64\' insgesamt sammeln?", "120", 500, false]]}, {"name": "Welt der Werbung", "questions": [["\'Quadratisch. Praktisch. Gut.\'", "Ritter Sport", 100, false], ["\'Dann klappt\'s auch mit dem Nachbarn.\'", "Erdal", 200, false], ["\'Wie gut, dass es Hornbach gibt.\'", "Hornbach", 300, false], ["\'Mein Haus, mein Auto, mein Boot.\'", "Sparkasse", 400, false], ["\'Daf\\u00fcr stehe ich mit meinem Namen.\'", "K\\u00e4pt\'n Iglo", 500, false]]}, {"name": "Brands", "questions": [["Welches Unternehmen hat die Fast-Food-Kette McDonald\'s gegr\\u00fcndet?", "Richard und Maurice McDonald", 100, false], ["Welches Unternehmen ist f\\u00fcr die Spielekonsole PlayStation verantwortlich?", "Sony", 200, false], ["Wie hei\\u00dft der Gr\\u00fcnder von Facebook?", "Mark Zuckerberg", 300, false], ["Wie hei\\u00dft der CEO von Berkshire Hathaway?", "Warren Buffett", 400, false], ["Wann wurde das Unternehmen IBM gegr\\u00fcndet?", "1911", 500, false]]}, {"name": "Filme und Serien", "questions": [["Welches Unternehmen produziert die Marvel Cinematic Universe Filme?", "Marvel Studios", 100, false], ["Wer spielte den Charakter Jack Dawson im Film \'Titanic\'?", "Leonardo DiCaprio", 200, false], ["Wie hei\\u00dft die animierte Serie, in der die Familie Simpson die Hauptrolle spielt?", "Die Simpsons", 300, false], ["Welche Serie dreht sich um das Leben und die Abenteuer von Agent Jack Bauer?", "24", 400, false], ["In welchem Jahr wurde der erste Film der \'Harry Potter\'-Reihe ver\\u00f6ffentlicht?", "2001", 500, false]]}, {"name": "Da fragt man sich", "questions": [["Diese Person ist der derzeitige CEO von Tesla.", "Wer ist Elon Musk?", 100, false], ["Diese Farbe entsteht durch das Mischen von Blau und Gelb.", "Was ist Gr\\u00fcn?", 200, false], ["Diese Hauptstadt liegt am Bosporus und verbindet Europa und Asien.", "Was ist Istanbul?", 300, false], ["Dieser Schriftsteller schrieb \'1984\' und \'Animal Farm\'.", "Wer ist George Orwell?", 400, false], ["Dieser Nobelpreis wird seit 1969 f\\u00fcr herausragende Leistungen in den Wirtschaftswissenschaften verliehen.", "Was ist der Alfred-Nobel-Ged\\u00e4chtnispreis f\\u00fcr Wirtschaftswissenschaften?", 500, false]]}]}', null=True),
        ),
    ]
