# Generated by Django 5.0.6 on 2024-05-18 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_lobby_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='started_time',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='board',
            field=models.JSONField(blank=True, default='{"Categories": [{"name": "Welt der Werbung", "questions": [["\'Haribo macht Kinder froh und Erwachsene ebenso.\'", "Haribo", 100, false], ["\'Dann klappt\'s auch mit dem Nachbarn.\'", "Erdal", 200, false], ["\'Der feine Unterschied.\'", "Hengstenberg", 300, false], ["\'Willst du viel, sp\\u00fcl mit ...\'", "Pril", 400, false], ["\'Sch\\u00f6nes bleibt.\'", "Villeroy & Boch", 500, false]]}, {"name": "Brands", "questions": [["Wann wurde YouTube gegr\\u00fcndet?", "2005", 100, false], ["Wie hei\\u00dft die Modemarke mit dem ber\\u00fchmten krokodilf\\u00f6rmigen Logo?", "Lacoste", 200, false], ["Wann wurde das Unternehmen Nike gegr\\u00fcndet?", "1971", 300, false], ["Wann wurde das Unternehmen Tesla gegr\\u00fcndet?", "2003", 400, false], ["Wann wurde das Unternehmen IBM gegr\\u00fcndet?", "1911", 500, false]]}, {"name": "Gaming", "questions": [["Welches Genre von Videospielen beinhaltet haupts\\u00e4chlich Tanz und Musik?", "Rhythmus-Spiele", 100, false], ["In welchem Jahr wurde das erste \'Grand Theft Auto\'-Spiel ver\\u00f6ffentlicht?", 1997, 200, false], ["Wie hei\\u00dft das Rollenspiel, das von Bethesda Game Studios entwickelt wurde und in der postapokalyptischen Zukunft spielt?", "Fallout", 300, false], ["Welches Spiel wurde 1998 ver\\u00f6ffentlicht und gilt als ein Pionier des Stealth-Genres?", "Metal Gear Solid", 400, false], ["In welchem Spiel spielt man als ein Hacktivist in einer Stadt mit dem fiktiven Namen DedSec?", "Watch Dogs 2", 500, false]]}, {"name": "Filme und Serien", "questions": [["Wie hei\\u00dft der Regisseur des Films \'Inception\'?", "Christopher Nolan", 100, false], ["Wer spielte den Charakter Jack Dawson im Film \'Titanic\'?", "Leonardo DiCaprio", 200, false], ["Wie hei\\u00dft die animierte Serie, in der die Familie Simpson die Hauptrolle spielt?", "Die Simpsons", 300, false], ["In welchem Jahr wurde der Film \'Der Herr der Ringe: Die Gef\\u00e4hrten\' ver\\u00f6ffentlicht?", "2001", 400, false], ["Wer f\\u00fchrte Regie bei dem Film \'Inception\'?", "Christopher Nolan", 500, false]]}, {"name": "Da fragt man sich", "questions": [["Diese Person ist der derzeitige CEO von Tesla.", "Wer ist Elon Musk?", 100, false], ["Diese Farbe entsteht durch das Mischen von Blau und Gelb.", "Was ist Gr\\u00fcn?", 200, false], ["Diese Zahl ist die Quadratwurzel von 144.", "Was ist 12?", 300, false], ["Diese Struktur ist bekannt als das \'Hirn\' der Zelle.", "Was ist der Zellkern?", 400, false], ["Dieser griechische Philosoph war der Lehrer von Alexander dem Gro\\u00dfen.", "Wer ist Aristoteles?", 500, false]]}]}', null=True),
        ),
    ]
