# Generated by Django 5.0.6 on 2024-05-19 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lobby_started_time_alter_lobby_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='question',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='board',
            field=models.JSONField(blank=True, default='{"Categories": [{"name": "Welt der Werbung", "questions": [["\'Quadratisch. Praktisch. Gut.\'", "Ritter Sport", 100, false], ["\'So muss Technik.\'", "Media Markt", 200, false], ["\'Die wahrscheinlich l\\u00e4ngste Praline der Welt.\'", "Ferrero (Duplo)", 300, false], ["\'So geht Bank heute.\'", "Deutsche Bank", 400, false], ["\'Sch\\u00f6nes bleibt.\'", "Villeroy & Boch", 500, false]]}, {"name": "Da fragt man sich", "questions": [["Das gr\\u00f6\\u00dfte Land der Welt nach Fl\\u00e4che.", "Was ist Russland?", 100, false], ["Dieser Planet ist der n\\u00e4chste zur Sonne.", "Was ist Merkur?", 200, false], ["Dieses Organ pumpt Blut durch den menschlichen K\\u00f6rper.", "Was ist das Herz?", 300, false], ["Diese Theorie beschreibt die Relativit\\u00e4t von Raum und Zeit.", "Was ist die Relativit\\u00e4tstheorie?", 400, false], ["Diese Komponistin und Pianistin war die Ehefrau von Robert Schumann.", "Wer ist Clara Schumann?", 500, false]]}, {"name": "Gaming", "questions": [["In welchem Spiel ist der Charakter \'Link\' der Protagonist?", "The Legend of Zelda", 100, false], ["Welches Spiel gilt als das meistverkaufte Videospiel aller Zeiten?", "Minecraft", 200, false], ["In welchem Jahr wurde die Xbox 360 von Microsoft ver\\u00f6ffentlicht?", "2005", 300, false], ["In welchem Spiel ist die \'Pip-Boy\' ein wesentliches Ausr\\u00fcstungsst\\u00fcck?", "Fallout", 400, false], ["Wie viele Sterne kann man in \'Super Mario 64\' insgesamt sammeln?", "120", 500, false]]}, {"name": "Filme und Serien", "questions": [["In welcher Stadt spielt die Serie \'Friends\'?", "New York", 100, false], ["In welchem Jahr wurde der erste \'Star Wars\'-Film ver\\u00f6ffentlicht?", "1977", 200, false], ["Wie hei\\u00dft die animierte Serie, in der die Familie Simpson die Hauptrolle spielt?", "Die Simpsons", 300, false], ["Welche Serie basiert auf dem Buch \'Das Lied von Eis und Feuer\' von George R. R. Martin?", "Game of Thrones", 400, false], ["In welchem Jahr wurde der erste Film der \'Harry Potter\'-Reihe ver\\u00f6ffentlicht?", "2001", 500, false]]}, {"name": "Brands", "questions": [["Wie hei\\u00dft der Gr\\u00fcnder von Microsoft?", "Bill Gates", 100, false], ["Welches Unternehmen ist f\\u00fcr die Spielekonsole PlayStation verantwortlich?", "Sony", 200, false], ["Welches Unternehmen hat die Kaffeehauskette Starbucks gegr\\u00fcndet?", "Jerry Baldwin, Zev Siegl und Gordon Bowker", 300, false], ["Welches Unternehmen produziert die Marke Pampers?", "Procter & Gamble", 400, false], ["Wie hei\\u00dft die Fluggesellschaft mit dem K\\u00fcrzel \'SQ\'?", "Singapore Airlines", 500, false]]}]}', null=True),
        ),
    ]
